In [1]:
from urllib.request import Request, urlopen
import pandas as pd
import requests
import numpy as np

In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support.expected_conditions import  visibility_of_element_located
import re
import pandas as pd
import os

In [3]:
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait


#launch url
all_jobTitle=[]
all_jobLocation=[]
all_jobSkills=[]
all_jobOrg=[]
all_jobCompanyName = []
all_jobTitle = []
all_joburl = []
all_jobTitle1 = []

driver = webdriver.Firefox(executable_path='C://Users//Arjun D H//geckodriver-v0.24.0-win64//geckodriver.exe')
df=pd.DataFrame(index=range(0,(len(all_jobTitle))),columns=['JobTitle','JobSalary','JobLocation','JobDescription','JobUrl','LogoUrl','JobCompanyName'])

 
for index in range(1,14):
    #url = "https://www.cv-library.co.uk/search-jobs?category=&distance=15&geo=&industry=&offset="+str(index*100)+"&order=sm&perpage=100&posted=&q=design&salarymax=&salarymin=&salarytype=annum&tempperm="
    url = "https://www.cv-library.co.uk/search-jobs?distance=15&geo=&industry=&offset="+str(index*25)+"&order=sm&posted=&q=Designer&salarymax=&salarymin=&salarytype=annum&tempperm=Contract"
    driver.get(url)    
    print(index)
    
    driver.implicitly_wait(10)
    
    jobTitle1 = driver.find_elements_by_xpath("/html[1]/body[1]/main[1]/div[1]/div[1]/div[2]/ol[1]/li/article[1]/div[1]/h2[1]/a[1]")
    jobLocation = driver.find_elements_by_xpath("/html[1]/body[1]/main[1]/div[1]/div[1]/div[2]/ol[1]/li/article[1]/div[1]/dl[1]/dd[2]")
    jobCompanyName = driver.find_elements_by_xpath("/html[1]/body[1]/main[1]/div[1]/div[1]/div[2]/ol[1]/li/article[1]/div[1]/dl[1]/dd[3]")
    jobTitle = driver.find_elements_by_xpath("//div[@class='job__main']")
    jobCompanyName = driver.find_elements_by_xpath("//dd[@class='job__details-value text--semibold']")
    #jobSkills = driver.find_elements_by_xpath("//*[@class='job-list-item-label-wrapper']")
    #jobLocation = driver.find_elements_by_xpath("//*[@class='location']")
    #jobSalary = driver.find_elements_by_xpath("//*[@class='salary']")
    #jobOrg = driver.find_elements_by_xpath("//*[@class='from']")
    #jobdesc = driver.find_elements_by_xpath("//*[@class='job-listing__description']")
    joburl = driver.find_elements_by_xpath("/html[1]/body[1]/main[1]/div[1]/div[1]/div[2]/ol[1]/li/article[1]/div[1]/h2[1]/a[1]")
    for j in joburl:
        all_joburl.append(j.get_attribute('href'))
    for tt in jobTitle:
        all_jobTitle1.append(tt.text)
    for m in jobLocation:
        all_jobLocation.append(m.text)
    for n in jobCompanyName:
        all_jobCompanyName.append(n.text)
    
driver.close()

1
2
3
4
5
6
7
8
9
10
11
12
13

In [4]:
all_jobTitle1[10]

'Systems Analyst Designer\nSalary:\n£450 - £550/day\nLocation:\nSalisbury, Wiltshire\nJob Type:\nContract, Temporary\nRole: Systems Analyst Designer. Contracting Authority: DSTL. Contract Length: 240 days. Location: Salisbury. IR35: INSCOPE. Pay Rate: £550p/d Umbrella Max. Security Clearance: DV (Please provide current sponsor and DOB. Description. Dstl requires two Systems Engineers to research, develop … more\nApply Now'

In [5]:
df=pd.DataFrame(index=range(0,(len(all_jobTitle1))),columns=['JobTitle','JobSalary','JobLocation','JobUrl','JobDescription','LogoUrl','JobCompanyName'])
#Bids = data = np.array(['g','e','e','k','s'])

#bidata = pd.Series(all_bids)

for idx,section in enumerate(all_jobTitle1):
    scn = section.split('\n')
    #if('Full-time' in scn[2]):
    try:
        df.iloc[idx,0]=scn[0] #job title
    except IndexError:
        df.iloc[idx,0]=np.nan
        
    
    if('£' in scn[2]):
        try:
            df.iloc[idx,1]=scn[2] #job title
        except IndexError:
            df.iloc[idx,1]=np.nan
    else:
        try:
            df.iloc[idx,2]=scn[3] #job title
        except IndexError:
            df.iloc[idx,2]=np.nan
            
    if('Location' in scn[1]):
        try:
            df.iloc[idx,2]=scn[2] #job title
        except IndexError:
            df.iloc[idx,2]=np.nan
    else:
        try:
            df.iloc[idx,2]=scn[4] #job title
        except IndexError:
            df.iloc[idx,2]=np.nan
    
    if('Job Type' in scn[5]):
        try:
            df.iloc[idx,3]=scn[6] #job title
        except IndexError:
            df.iloc[idx,3]=np.nan
    else:
        try:
            df.iloc[idx,3]=scn[4] #job title
        except IndexError:
            df.iloc[idx,3]=np.nan
            
    if('Job Type' in scn[5]):
        try:
            df.iloc[idx,4]=scn[7] #job title
        except IndexError:
            df.iloc[idx,4]=np.nan
    else:
        try:
            df.iloc[idx,4]=scn[5] #job title
        except IndexError:
            df.iloc[idx,4]=np.nan

IndexError: list index out of range

In [6]:
df['JobUrl'] = pd.Series(all_joburl)
df['JobCompanyName'] = pd.Series(all_jobCompanyName)
df['LogoUrl'] = "https://www.cv-library.co.uk/assets/images/cvdb/britishjobs-network-logo-4513ab5121d0fa993c824d91830786cd2f201cd9d1deb45d12cc61c6b72f7f13.png"

In [7]:
df

,JobTitle,JobSalary,JobLocation,JobUrl,JobDescription,LogoUrl,JobCompanyName
0,Piping Designer,NaN,"Winchester, Hampshire",https://www.cv-library.co.uk/job/210971772/Pip...,Piping Designer Services are required for our ...,https://www.cv-library.co.uk/assets/images/cvd...,Millbank Holdings
1,Content Designer,£100 - £200/day,Edinburgh,https://www.cv-library.co.uk/job/211098718/Con...,… are working with our public sector client to...,https://www.cv-library.co.uk/assets/images/cvd...,Pertemps - Edinburgh Commercial
2,Senior Designer,£350 - £400/day,"City of London, London",https://www.cv-library.co.uk/job/211094492/Sen...,A Global Technology Company based in London ar...,https://www.cv-library.co.uk/assets/images/cvd...,Huntress
3,Piping Designer,NaN,South East,https://www.cv-library.co.uk/job/211026911/Pip...,Working within a multidisciplinary team with e...,https://www.cv-library.co.uk/assets/images/cvd...,Insite Resourcing
4,Senior Designer,NaN,"Whitehaven, Cumbria",https://www.cv-library.co.uk/job/211083592/Sen...,Has contributed to Designers Risk Assessments ...,https://www.cv-library.co.uk/assets/images/cvd...,Orion Group
5,PCB Altium Designer,NaN,Highlands,https://www.cv-library.co.uk/job/211114878/PCB...,FINTEC recruit is seeking a PCB Altium Designe...,https://www.cv-library.co.uk/assets/images/cvd...,FINTEC recruit Ltd
6,Senior Designer,£396/day,London,https://www.cv-library.co.uk/job/211097337/Sen...,Senior Designer - London. 8 Month contract. £3...,https://www.cv-library.co.uk/assets/images/cvd...,Advantage Resourcing
7,Instrument Designer,NaN,"Aberdeen, Aberdeen City",https://www.cv-library.co.uk/job/210861494/Ins...,"Working as part of a design team, the Senior D...",https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy
8,Training Designer,NaN,"PO6, Hilsea, Portsmouth",https://www.cv-library.co.uk/job/211002335/Tra...,Training Designer. Contract. 6 months plus. Ba...,https://www.cv-library.co.uk/assets/images/cvd...,First Recruitment Group
9,Graphic Designer,NaN,"Edinburgh, City of Edinburgh",https://www.cv-library.co.uk/job/211029345/Gra...,"Graphic Designer. Location: Edinburgh, Mid Lot...",https://www.cv-library.co.uk/assets/images/cvd...,Vision Events
10,Systems Analyst Designer,£450 - £550/day,"Salisbury, Wiltshire",https://www.cv-library.co.uk/job/211102991/Sys...,Role: Systems Analyst Designer. Contracting Au...,https://www.cv-library.co.uk/assets/images/cvd...,Netforte Group
11,Graphic Designer,"£8,494/annum Internal training, free entry to ...",Paignton Zoo,https://www.cv-library.co.uk/job/210963451/Gra...,Exciting opportunity to join our busy creative...,https://www.cv-library.co.uk/assets/images/cvd...,Paignton Zoo
12,Civil Structural Designer,£32.00 - £34.00/hour,Cheshire,https://www.cv-library.co.uk/job/210972182/Civ...,We are looking for a Civil Structural Designer...,https://www.cv-library.co.uk/assets/images/cvd...,GPW Recruitment
13,Interior Designer,"£25,000 - £30,000/annum",Northamptonshire,https://www.cv-library.co.uk/job/211077290/Int...,"Interior Designer. Northamptonshire. £25,000 -...",https://www.cv-library.co.uk/assets/images/cvd...,ARV Solutions Contracts
14,Interior Designer,£36 - £37/hour,"Gaydon, Warwickshire",https://www.cv-library.co.uk/job/211081376/Int...,Position: Interior Designer. The role of an In...,https://www.cv-library.co.uk/assets/images/cvd...,Envisage Recruitment Limited
15,Senior Structural Designer,NaN,London,https://www.cv-library.co.uk/job/210991237/Sen...,… a requirement for a Senior Structural Design...,https://www.cv-library.co.uk/assets/images/cvd...,Raeburn Recruitment
16,Senior Mechanical Designer,£27.00 - £28.00/hour,"Barrow-In-Furness, Cumbria Also in other locat...",https://www.cv-library.co.uk/job/211069038/Sen...,Join a world-renowned aerospace and defence or...,https://www.cv-library.co.uk/assets/images/cvd...,JAM Recruitment Ltd
17,Mechanical/ Piping Designer,NaN,County Durham,https://www.cv-library.co.uk/job/209586080/Mec...,Mechanical/ Piping Designer - Contract - Chemi...,https://www.cv-library.co.uk/assets/images/cvd...,Adepto Technical
18,Expert Surface Designer,NaN,Göteborg,https://www.cv-library.co.uk/job/211046348/Exp...,Automotive client based in Sweden are looking ...,https://www.cv-library.co.uk/assets/images/cvd...,Futura Design
19,Senior Piping Designer,NaN,Scotland Also in other locations,https://www.cv-library.co.uk/job/211078857/Sen...,NES are looking for a Senior Piping Designer w...,https://www.cv-library.co.uk/assets/images/cvd...,NES Global Talent
20,Contract TEKLA Designer,£27 - £30/hour,London,https://www.cv-library.co.uk/job/211085623/Con...,We have an urgent requirement for a TEKLA Desi...,https://www.cv-library.co.uk/assets/images/cvd...,Cotleigh Engineering
21,Mechanical / Piping Designer,NaN,Greater Manchester,https://www.cv-library.co.uk/job/211118761/Mec...,Our client who has a chemical manufacturing pl...,https://www.cv-library.co.uk/assets/images/cvd...,Adepto Technical
22,PDMS EC&I Designer,NaN,Warrington,https://www.cv-library.co.uk/job/210953947/PDM...,NRL are currently looking for an EC&I Designer...,https://www.cv-library.co.uk/assets/images/cvd...,NRL
23,Pattern Cutter & Designer,"£27,000 - £35,000/annum",London,https://www.cv-library.co.uk/job/211031270/Pat...,CREATIVE PATTERN CUTTER / Designer. May are St...,https://www.cv-library.co.uk/assets/images/cvd...,May & Stephens
24,Instructional Designer,£39 - £39.37/hour,"Portsmouth, Hampshire",https://www.cv-library.co.uk/job/211012083/Ins...,"Due to continued investment, this manufacturin...",https://www.cv-library.co.uk/assets/images/cvd...,JAM Recruitment Ltd
25,Electrical Designer,NaN,Belgium,https://www.cv-library.co.uk/job/211004169/Ele...,Electrical Designer - Belgium. Electrical Desi...,https://www.cv-library.co.uk/assets/images/cvd...,X4 Group Ltd
26,Electrical Designer,£39/hour,"KT22, Leatherhead, Surrey",https://www.cv-library.co.uk/job/210965918/Ele...,Experienced Electrical CAD Designer required f...,https://www.cv-library.co.uk/assets/images/cvd...,Donovan Marrison Ltd
27,Electrical Designer,£17.25 - £22.00/hour,"Rosyth, Fife",https://www.cv-library.co.uk/job/210957485/Ele...,Electrical Designers are required for work sta...,https://www.cv-library.co.uk/assets/images/cvd...,Orion Group
28,Web Designer,£150 - £300/day,Baldock,https://www.cv-library.co.uk/job/211125857/Web...,I have an opportunity for experienced Web Desi...,https://www.cv-library.co.uk/assets/images/cvd...,Interaction Recruitment
29,Webmethods Application Designer / Developer,£500 - £530/day,"Chesterfield, Derbyshire",https://www.cv-library.co.uk/job/210976104/Web...,Webmethods Application Designer / Developer. 6...,https://www.cv-library.co.uk/assets/images/cvd...,CBSbutler c/o Staffing 360 Solutions Limited
...,...,...,...,...,...,...,...
295,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210967293/Pro...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,"CK Group- Science, Clinical and Technical"
296,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211091216/Des...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Crewit Resourcing Ltd
297,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210800991/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy
298,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210903345/Lea...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy
299,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211037815/Tec...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Gold Group
300,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211114237/Tes...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Outsource UK Ltd
301,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211126512/Dig...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Colbern Limited
302,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211116151/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy
303,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210800991/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy
304,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210903345/Lea...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy
305,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210992018/Sha...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Capita Resourcing
306,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211064931/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Engineering Production
307,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210767140/War...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,DYNAMIC RESOURCING
308,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211051657/Pro...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Premea
309,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211083100/Tun...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Skilled Careers
310,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210967105/Bui...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Roevin
311,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210983460/Jun...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Carmichael UK
312,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211076477/Des...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Genesis Technical Recruitment Ltd
313,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211018688/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,People Source Consulting
314,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211053863/IT-...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Human Capital Ventures
315,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211005557/Mar...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Hunter Merrifield
316,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210862183/Sof...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,MASS
317,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210924902/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy
318,NaN,NaN,NaN,https://www.cv-library.co.uk/job/210955308/Mos...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Adecco
319,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211058031/M-E...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,First People Solutions
320,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211055099/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Jonathan Lee Recruitment Ltd
321,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211051877/Pro...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Care Soft Global
322,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211021615/Dra...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,BBL Technical Recruitment Limited
323,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211069103/Sen...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,Maritime
324,NaN,NaN,NaN,https://www.cv-library.co.uk/job/211082762/Lea...,NaN,https://www.cv-library.co.uk/assets/images/cvd...,PD&MS Energy

In [8]:
#df['JobCompanyName'] = pd.Series(complete_text)
df["isForFreeUsers"]="No"

In [9]:
list1 = ['UI','CSS','ADOBE','PYTHON','JAVA','MAVEN','JAVASCRIPT','UX','GRAPHIC DESIGN', 'HTML', 'PHP', 'WEB DESIGN','lOGO DESIGN','PHOTOSHOP','ILLUSTOR','FRONT END','BACK END','ANIMATION','VFX']
list2 = []
list3 = []

In [10]:
ser = pd.Series(df['JobDescription']) 
ser = ser.apply(lambda x:x.upper())

AttributeError: 'float' object has no attribute 'upper'

In [11]:
for items in ser:
    list2 = []
    #print(items)
    for i in list1:
        #print(i)
        if i in items:
            list2.append(i)
    print(list2)
    list3.append(list2)

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['GRAPHIC DESIGN']
[]
[]
[]
['UX']
[]
[]
[]
['UX']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['UI']
[]
[]
[]
['UI', 'UX']
[]
[]
[]
[]
['UX']
['UX']
['UI', 'UX']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['UI', 'UX']
[]
['UX']
['UX']
[]
[]
[]
['UI', 'UX']
[]
[]
[]
[]
['UI']
['UI', 'UX']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['UX']
[]
[]
[]
['UX']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['UX']
[]
[]
[]
[]
[]

TypeError: argument of type 'float' is not iterable

In [ ]:
df['JobSkills'] = pd.Series(list3)

In [ ]:
df['JobSkills'] = df['JobSkills'].apply(lambda x:' , '.join([str(elem) for elem in x]))

In [ ]:
df['JobSource'] = "cv-library"

In [ ]:
df

In [ ]:
df['JobSkills'].replace('', np.nan, inplace=True)

In [ ]:
df['JobCompanyName'] = df['JobCompanyName'].apply(lambda x:x.replace('From ',''))

In [ ]:
df.shape

In [ ]:
df['JobUrl'].nunique()

In [ ]:
df = df.drop_duplicates()

In [ ]:
df['JobUrl'].value_counts(ascending=False)

In [ ]:
df.to_csv('/Users/Arjun D H/Documents/CVLibrary1.csv',header=True)

In [ ]:
df['JobUrl'].nunique()

In [ ]:
df['JobUrl'].value_counts(ascending=False)

In [ ]:
valcnt=df['JobUrl'].value_counts()

In [ ]:
valcnt

In [ ]:
valcnt1=valcnt[valcnt > 1]

In [ ]:
valcnt1

In [ ]:
valcnt1=valcnt1.reset_index()

In [ ]:
valcnt1

In [ ]:
valcnt1.columns=['JobUrl','Frequency']

In [ ]:
valcnt1

In [ ]:
valcnt1 = valcnt1.drop_duplicates()

In [ ]:
valcnt1

In [ ]:
dupjoburl=list(valcnt1['JobUrl'])

In [ ]:
len(dupjoburl)

In [ ]:
data21=df[~df.JobUrl.isin(dupjoburl)]

In [ ]:
data21['JobUrl'].value_counts()

In [ ]:
if len(dupjoburl)==0:
    df.to_csv('/Users/Arjun D H/Documents/CVLibrary1.csv',header=True)
else:
    driver = webdriver.Firefox(executable_path='C://Users//Arjun D H//geckodriver-v0.24.0-win64//geckodriver.exe')
    #complete_text = []
    all_jobCompanyName1=[]
    all_jobTitle=[]
    all_jobTitle2=[]
    all_jobSalary=[]
    all_jobLocation11=[]
    all_jobDescription=[]
    for item in dupjoburl:
        driver.get(item)
        driver.implicitly_wait(10)
        jobTitle2 = driver.find_elements_by_xpath("//div[@class='job__main job-card']")
        jobSalary = driver.find_elements_by_xpath("/html[1]/body[1]/main[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/header[1]/dl[1]/dd[1]")
        jobCompanyName1 = driver.find_elements_by_xpath("//dd[@class='job__title job__details-value']")
        jobTitle = driver.find_elements_by_xpath("//h1[@class='job__title job__details-value']")
        jobDescription = driver.find_elements_by_xpath("//div[@class='job__description job__details-value']")
        jobLocation11 = driver.find_elements_by_xpath("/html[1]/body[1]/main[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/header[1]/dl[1]/dd[2]")
        
        
        for j in jobDescription:
            all_jobDescription.append(j.text)
        for tt in jobTitle:
            all_jobTitle.append(tt.text)
        for m in jobSalary:
            all_jobSalary.append(m.text)
        for n in jobCompanyName1:
            all_jobCompanyName1.append(n.text)
        for tt in jobTitle2:
            all_jobTitle2.append(tt.text)
        for t in jobLocation11:
            all_jobLocation11.append(t.text)    
driver.close()

In [ ]:
all_jobTitle2[0]

In [ ]:
scn[6]

In [ ]:
df2=pd.DataFrame(index=range(0,(len(all_jobTitle2))),columns=['JobTitle','JobSalary','JobCompanyName','JobUrl','JobDescription','LogoUrl','JobLocation'])
#Bids = data = np.array(['g','e','e','k','s'])

#bidata = pd.Series(all_bids)

for idx,section in enumerate(all_jobTitle2):
    scn = section.split('\n')
    #if('Full-time' in scn[2]):
    try:
        df2.iloc[idx,0]=scn[2] #job title
    except IndexError:
        df2.iloc[idx,0]=np.nan
        
    
    if('£' in scn[4]):
        try:
            df2.iloc[idx,1]=scn[4] #job title
        except IndexError:
            df2.iloc[idx,1]=np.nan
    else:
        try:
            df2.iloc[idx,1]=scn[3] #job title
        except IndexError:
            df2.iloc[idx,1]=np.nan
            
    if('CompanyName' in scn[8]):
        try:
            df2.iloc[idx,2]=scn[8] #job title
        except IndexError:
            df2.iloc[idx,2]=np.nan
    else:
        try:
            df2.iloc[idx,2]=scn[10] #job title
        except IndexError:
            df2.iloc[idx,2]=np.nan

In [ ]:
df2['JobUrl'] = pd.Series(all_joburl)
df2['JobLocation'] = pd.Series(all_jobLocation11)
df2['LogoUrl'] = "https://www.cv-library.co.uk/assets/images/cvdb/britishjobs-network-logo-4513ab5121d0fa993c824d91830786cd2f201cd9d1deb45d12cc61c6b72f7f13.png"

In [ ]:
df2['JobSource'] = "cv-library"

In [ ]:
#df2['JobCompanyName'] = pd.Series(all_jobCompanyName1)
#df2['JobTitle'] = pd.Series(all_jobTitle)
df2['JobDescription'] = pd.Series(all_jobDescription)

In [ ]:
df2

In [ ]:
df2 = df2[df2.JobSalary != 'Location']

In [ ]:
df2

In [ ]:
df1=df[~df.JobUrl.isin(dupjoburl)]

In [ ]:
df1

In [ ]:
df1.shape

In [ ]:
df1['JobUrl'].value_counts(ascending=False)

In [ ]:
df3 = pd.concat([df2,df1],axis=0)

In [ ]:
df3

In [ ]:
df3['JobUrl'].nunique()

In [ ]:
df3.shape

In [ ]:
df3 = df3.drop_duplicates()

In [ ]:
df3.shape

In [ ]:
df3['JobUrl'].value_counts(ascending=False)

In [ ]:
df1["ForFreeUsers"]="0"

In [ ]:
df1.to_csv('/Users/Arjun D H/Documents/CVLibrary1.csv',header=True)